"""
resources/manager.py — In-memory reference-counted asset cache.

The ``ResourceManager`` is the single gateway for loading hand-crafted assets
(models, audio, static textures).  Procedural environment textures do NOT
route here — they come from the Procedural API (see ARCHITECTURE.md §5.3).

Refcount Semantics
------------------
- ``load(path)`` returns a ``Handle`` at **refcount 0**.
  The caller must call ``acquire(handle)`` to express ownership, incrementing
  the refcount to 1.  This matches a "you requested it; you must claim it"
  ownership model and makes it easy for a system to load-without-owning (e.g.
  pre-warm cache), then have each consumer ``acquire``.

- ``acquire(handle)`` increments the refcount by 1.
- ``release(handle)`` decrements the refcount by 1; refcount never goes below 0.
- ``unload_unreferenced()`` evicts all handles whose refcount is 0.

Typical usage for a consumer that wants to own an asset::

    handle = manager.load("assets/models/landmark.egg")
    manager.acquire(handle)    # refcount → 1; caller now owns a reference
    model = handle.resource    # the live Panda3D NodePath (or whatever the loader returned)
    ...
    manager.release(handle)    # refcount → 0 when all owners are done
    manager.unload_unreferenced()  # evicts the handle

Loader Injection (Inversion of Control)
----------------------------------------
``ResourceManager`` holds a reference to the **loaders** module (default:
``fire_engine.resources.loaders``).  This default is overridable in the
constructor for testing — inject a custom object with ``dispatch`` and
``register_loader`` callables to test the manager in complete isolation from
panda3d.

The real panda3d-backed loaders are registered into
``fire_engine.resources.loaders`` at boot by
``world.resource_adapter.register_panda_loaders(manager)``.

Path Normalisation
------------------
All paths are normalised via ``os.path.normcase(os.path.normpath(path))``
before cache lookup, so ``assets\\models\\foo.egg`` and
``assets/models/foo.egg`` hit the same cache entry.
"""

from __future__ import annotations

import os
from typing import Any, Optional, Protocol, runtime_checkable

import fire_engine.resources.loaders as _default_loaders_module


# ---------------------------------------------------------------------------
# Handle
# ---------------------------------------------------------------------------

class Handle:
    """
    A reference-counted wrapper around a loaded resource.

    Attributes
    ----------
    resource : object
        The raw loaded object (e.g. a Panda3D ``NodePath``, ``AudioSound``,
        Pillow ``Image``, or whatever the registered loader returned).
    path : str
        Normalised path string used as the cache key.
    refcount : int
        Current reference count.  Starts at 0 on construction.  Call
        ``ResourceManager.acquire(handle)`` to increment,
        ``ResourceManager.release(handle)`` to decrement.

    Example
    -------
        handle = manager.load("assets/models/player_hands.egg")
        manager.acquire(handle)
        obj = handle.resource   # live resource
        manager.release(handle)
    """

    __slots__ = ("resource", "path", "refcount")

    def __init__(self, resource: Any, path: str) -> None:
        self.resource: Any  = resource
        self.path:     str  = path
        self.refcount: int  = 0

    def __repr__(self) -> str:
        return (
            f"Handle(path={self.path!r}, refcount={self.refcount}, "
            f"resource={type(self.resource).__name__})"
        )


# ---------------------------------------------------------------------------
# LoadersModule protocol — for type-safe injection in tests
# ---------------------------------------------------------------------------

@runtime_checkable
class _LoadersModule(Protocol):
    """Structural type that the loaders module and test fakes must satisfy."""

    def dispatch(self, path: str) -> Any: ...
    def register_loader(self, suffix: str, loader: Any) -> None: ...


# ---------------------------------------------------------------------------
# ResourceManager
# ---------------------------------------------------------------------------

class ResourceManager:
    """
    Central cache and dispatcher for hand-crafted asset loading.

    All file I/O for assets goes through this class.  The manager:
    - Normalises the path.
    - On cache miss: calls ``loaders.dispatch(path)`` to load the resource.
    - Wraps the result in a ``Handle`` (refcount=0) and caches it.
    - On cache hit: returns the **same** ``Handle`` instance.
    - Provides acquire/release refcounting and ``unload_unreferenced()``.

    Procedural environment textures explicitly do NOT route here; they are
    generated by the Procedural API and bridged into panda3d via
    ``world/texture_bridge.py``.

    Parameters
    ----------
    loaders_module : optional
        The module that provides ``dispatch(path)`` and
        ``register_loader(suffix, fn)``.  Defaults to
        ``fire_engine.resources.loaders``.  Override in tests to inject a
        fake module so the manager can be exercised without panda3d.

    Example
    -------
        # Boot sequence (world/app.py):
        from fire_engine.resources import manager as resource_manager_module
        from fire_engine.render.resource_adapter import register_panda_loaders

        # 1. Register real panda3d loaders into the default loaders module
        register_panda_loaders(resource_manager_module.default_manager)

        # 2. Use the global convenience instance
        from fire_engine.resources import load, acquire, release
        handle = load("assets/models/landmark_church.egg")
        acquire(handle)
        nodepath = handle.resource
    """

    def __init__(
        self,
        loaders_module: Optional[Any] = None,
    ) -> None:
        # If no loaders module is injected, use the real module-level one.
        self._loaders = loaders_module if loaders_module is not None else _default_loaders_module
        # Cache: normalised path → Handle
        self._cache: dict[str, Handle] = {}

    # ------------------------------------------------------------------
    # Core loading
    # ------------------------------------------------------------------

    def load(self, path: str) -> Handle:
        """
        Load an asset by path, returning a cached ``Handle``.

        On cache miss the loader registered for the file suffix is invoked
        and the result is wrapped in a new ``Handle`` (refcount=0).
        On cache hit the existing ``Handle`` is returned unchanged (refcount
        is not modified — call ``acquire`` to express ownership).

        Parameters
        ----------
        path : str
            File path.  May be relative or absolute.  Normalised before lookup.

        Returns
        -------
        Handle
            A ``Handle`` wrapping the loaded resource.  Always the SAME
            instance for the same normalised path.

        Raises
        ------
        UnknownResourceFormatError
            If no loader is registered for the file's suffix.

        Example
        -------
            handle = manager.load("assets/models/church.egg")
            manager.acquire(handle)
            nodepath = handle.resource
        """
        key = self._normalise(path)
        if key in self._cache:
            return self._cache[key]

        # Pass the normalised-but-case-preserved path to the loader so that
        # file system lookups (e.g. Panda3D on Windows) receive the correct
        # mixed-case path.  The cache key is the normcase version (for
        # case-insensitive de-duplication on Windows), but the actual file
        # I/O uses a path whose separators are normalised yet case is preserved.
        load_path = os.path.normpath(path)
        resource  = self._loaders.dispatch(load_path)
        handle    = Handle(resource=resource, path=key)
        self._cache[key] = handle
        return handle

    # ------------------------------------------------------------------
    # Refcounting
    # ------------------------------------------------------------------

    def acquire(self, handle: Handle) -> Handle:
        """
        Increment the reference count of *handle* by 1.

        Call once for each owner that wants to express it holds a live
        reference.  Paired with ``release`` when done.

        Parameters
        ----------
        handle : Handle
            Must be a Handle returned by ``load()`` on this manager.

        Returns
        -------
        Handle
            The same handle (for chaining: ``h = manager.acquire(manager.load(p))``).

        Example
        -------
            handle = manager.load("assets/audio/ambient.ogg")
            manager.acquire(handle)   # refcount → 1
        """
        handle.refcount += 1
        return handle

    def release(self, handle: Handle) -> None:
        """
        Decrement the reference count of *handle* by 1.

        The refcount is clamped to 0 and never goes negative.  When the
        refcount reaches 0 the handle is eligible for eviction on the next
        ``unload_unreferenced()`` call.

        Parameters
        ----------
        handle : Handle
            A Handle whose ``acquire`` was previously called on this manager.

        Example
        -------
            manager.release(handle)   # refcount → 0
            manager.unload_unreferenced()  # handle evicted from cache
        """
        if handle.refcount > 0:
            handle.refcount -= 1

    # ------------------------------------------------------------------
    # Cache maintenance
    # ------------------------------------------------------------------

    def unload_unreferenced(self) -> int:
        """
        Evict all cached ``Handle`` objects whose refcount is 0.

        If the resource object exposes a ``cleanup()`` method it is called
        before removal (allows panda3d NodePaths to remove themselves from the
        scene graph, etc.).

        Returns
        -------
        int
            The number of handles that were evicted.

        Example
        -------
            manager.release(handle_a)
            n = manager.unload_unreferenced()
            # handle_a is gone; any handle with refcount > 0 remains.
        """
        to_remove = [key for key, h in self._cache.items() if h.refcount == 0]
        for key in to_remove:
            handle = self._cache.pop(key)
            # Best-effort cleanup hook (e.g. NodePath.remove_node)
            cleanup = getattr(handle.resource, "cleanup", None)
            if callable(cleanup):
                try:
                    cleanup()
                except Exception:  # noqa: BLE001
                    pass
        return len(to_remove)

    # ------------------------------------------------------------------
    # Diagnostics
    # ------------------------------------------------------------------

    def stats(self) -> dict:
        """
        Return a summary of the current cache state.

        Returns
        -------
        dict with keys:
            ``"cache_size"``    : int  — total number of cached handles.
            ``"total_handles"`` : int  — same as cache_size (each path has 1 handle).
            ``"zero_ref"``      : int  — handles with refcount == 0 (eviction candidates).
            ``"nonzero_ref"``   : int  — handles with refcount > 0 (actively owned).
            ``"max_refcount"``  : int  — highest single refcount (0 if cache empty).
            ``"total_refcount"``: int  — sum of all refcounts.

        Example
        -------
            s = manager.stats()
            print(s["cache_size"])   # e.g. 4
            print(s["zero_ref"])     # e.g. 1  (ready to evict)
        """
        handles = list(self._cache.values())
        refcounts = [h.refcount for h in handles]
        return {
            "cache_size":     len(handles),
            "total_handles":  len(handles),
            "zero_ref":       sum(1 for r in refcounts if r == 0),
            "nonzero_ref":    sum(1 for r in refcounts if r > 0),
            "max_refcount":   max(refcounts) if refcounts else 0,
            "total_refcount": sum(refcounts),
        }

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------

    @staticmethod
    def _normalise(path: str) -> str:
        """
        Normalise *path* to a stable cache key.

        Uses ``os.path.normcase(os.path.normpath(path))`` so that
        ``assets\\models\\foo.egg`` and ``assets/models/foo.egg``
        resolve to the same key.

        Parameters
        ----------
        path : str

        Returns
        -------
        str  — normalised path string.
        """
        return os.path.normcase(os.path.normpath(path))

    def __repr__(self) -> str:
        return f"ResourceManager(cache_size={len(self._cache)})"


# ---------------------------------------------------------------------------
# Module-level default instance + convenience functions
# ---------------------------------------------------------------------------

#: Global default ``ResourceManager``.  Use this unless you need an isolated
#: instance (e.g. in tests).  ``world/resource_adapter.register_panda_loaders``
#: registers loaders into the underlying ``loaders`` module, which this
#: instance dispatches through.
default_manager: ResourceManager = ResourceManager()


def load(path: str) -> Handle:
    """
    Load *path* through the default ``ResourceManager``.

    Convenience wrapper for ``default_manager.load(path)``.
    See ``ResourceManager.load`` for full documentation.

    Example
    -------
        from fire_engine.resources import load, acquire
        handle = acquire(load("assets/models/church.egg"))
        nodepath = handle.resource
    """
    return default_manager.load(path)


def acquire(handle: Handle) -> Handle:
    """
    Increment the refcount of *handle* via the default manager.

    Convenience wrapper for ``default_manager.acquire(handle)``.

    Example
    -------
        handle = acquire(load("assets/audio/wind.ogg"))
    """
    return default_manager.acquire(handle)


def release(handle: Handle) -> None:
    """
    Decrement the refcount of *handle* via the default manager.

    Convenience wrapper for ``default_manager.release(handle)``.
    """
    default_manager.release(handle)


def unload_unreferenced() -> int:
    """
    Evict all zero-refcount handles from the default manager.

    Returns the number of evicted handles.
    """
    return default_manager.unload_unreferenced()
