"""Protocol codegen — single source (schema.json) -> Python + TypeScript bindings.

Run from anywhere:

    python editor/protocol/codegen.py

Produces (both committed; regenerated whenever schema.json changes — EDITOR_PRD
hard rule 6):

    editor/fire_editor/_generated.py
    editor/extension/src/protocol/generated.ts

The generated files carry constants (protocol version, binary magic/header,
schema ids, JSON-RPC error codes), method/notification name constants, and
typed param/result shapes (TypedDict on Python, interface on TS). They are the
ONLY place the two languages agree on the wire format; never hand-edit them.
"""
from __future__ import annotations

import json
from pathlib import Path

HERE = Path(__file__).resolve().parent
SCHEMA_PATH = HERE / "schema.json"
PY_OUT = HERE.parent / "fire_editor" / "_generated.py"
TS_OUT = HERE.parent / "extension" / "src" / "protocol" / "generated.ts"

_PY_TYPES = {
    "int": "int",
    "str": "str",
    "bool": "bool",
    "float": "float",
    "any": "object",
}
_TS_TYPES = {
    "int": "number",
    "str": "string",
    "bool": "boolean",
    "float": "number",
    "any": "unknown",
}

_BANNER = "AUTOGENERATED by editor/protocol/codegen.py from schema.json — DO NOT EDIT."


def _const_name(method: str) -> str:
    return method.upper().replace(".", "_")


def _load() -> dict:
    return json.loads(SCHEMA_PATH.read_text(encoding="utf-8"))


def gen_python(schema: dict) -> str:
    magic = int(schema["binary"]["magic_hex"], 16)
    lines: list[str] = []
    w = lines.append
    w(f'"""{_BANNER}"""')
    w("from __future__ import annotations")
    w("")
    w("from typing import NotRequired, TypedDict")
    w("")
    w(f'PROTOCOL_VERSION = {schema["protocol_version"]}')
    w(f'DAEMON_VERSION = "{schema["daemon_version"]}"')
    w("")
    w("# Binary framing: [u32 magic][u32 schema_id][u32 payload_id][payload], little-endian.")
    w(f"BINARY_MAGIC = {magic}  # {schema['binary']['magic_hex']}")
    w(f"BINARY_HEADER_SIZE = {schema['binary']['header_size']}")
    w("")
    w("class SchemaId:")
    for k, v in schema["binary"]["schemas"].items():
        w(f"    {k} = {v}")
    w("")
    w("class ErrorCode:")
    for k, v in schema["errors"].items():
        w(f"    {k} = {v}")
    w("")
    w("class Method:")
    for m in schema["methods"]:
        w(f'    {_const_name(m)} = "{m}"')
    w("")
    w("class Notification:")
    for n in schema["notifications"]:
        w(f'    {_const_name(n)} = "{n}"')
    w("")
    for m, spec in schema["methods"].items():
        cls = "".join(p.capitalize() for p in m.replace(".", "_").split("_"))
        for kind in ("params", "result"):
            fields = spec.get(kind, {})
            w(f"class {cls}{kind.capitalize()}(TypedDict):")
            if not fields:
                w("    pass")
            for fname, ftype in fields.items():
                optional = fname.endswith("?")
                clean = fname[:-1] if optional else fname
                ty = _PY_TYPES[ftype]
                if optional:
                    ty = f"NotRequired[{ty}]"
                w(f"    {clean}: {ty}")
            w("")
    return "\n".join(lines) + "\n"


def gen_typescript(schema: dict) -> str:
    magic = int(schema["binary"]["magic_hex"], 16)
    lines: list[str] = []
    w = lines.append
    w(f"// {_BANNER}")
    w("/* eslint-disable */")
    w("")
    w(f"export const PROTOCOL_VERSION = {schema['protocol_version']};")
    w(f'export const DAEMON_VERSION = "{schema["daemon_version"]}";')
    w("")
    w("// Binary framing: [u32 magic][u32 schema_id][u32 payload_id][payload], little-endian.")
    w(f"export const BINARY_MAGIC = {magic}; // {schema['binary']['magic_hex']}")
    w(f"export const BINARY_HEADER_SIZE = {schema['binary']['header_size']};")
    w("")
    w("export const SchemaId = {")
    for k, v in schema["binary"]["schemas"].items():
        w(f"  {k}: {v},")
    w("} as const;")
    w("")
    w("export const ErrorCode = {")
    for k, v in schema["errors"].items():
        w(f"  {k}: {v},")
    w("} as const;")
    w("")
    w("export const Method = {")
    for m in schema["methods"]:
        w(f'  {_const_name(m)}: "{m}",')
    w("} as const;")
    w("")
    w("export const Notification = {")
    for n in schema["notifications"]:
        w(f'  {_const_name(n)}: "{n}",')
    w("} as const;")
    w("")
    for m, spec in schema["methods"].items():
        cls = "".join(p.capitalize() for p in m.replace(".", "_").split("_"))
        for kind in ("params", "result"):
            fields = spec.get(kind, {})
            w(f"export interface {cls}{kind.capitalize()} {{")
            for fname, ftype in fields.items():
                optional = fname.endswith("?")
                clean = fname[:-1] if optional else fname
                w(f"  {clean}{'?' if optional else ''}: {_TS_TYPES[ftype]};")
            w("}")
            w("")
    return "\n".join(lines) + "\n"


def main() -> None:
    schema = _load()
    PY_OUT.write_text(gen_python(schema), encoding="utf-8")
    TS_OUT.parent.mkdir(parents=True, exist_ok=True)
    TS_OUT.write_text(gen_typescript(schema), encoding="utf-8")
    print(f"wrote {PY_OUT}")
    print(f"wrote {TS_OUT}")


if __name__ == "__main__":
    main()
