// AUTOGENERATED by editor/protocol/codegen.py from schema.json — DO NOT EDIT.
/* eslint-disable */

export const PROTOCOL_VERSION = 1;
export const DAEMON_VERSION = "0.1.0";

// Binary framing: [u32 magic][u32 schema_id][u32 payload_id][payload], little-endian.
export const BINARY_MAGIC = 1179210309; // 0x46495245
export const BINARY_HEADER_SIZE = 12;

export const SchemaId = {
  MESH: 1,
  TEXTURE: 2,
} as const;

export const ErrorCode = {
  PARSE_ERROR: -32700,
  INVALID_REQUEST: -32600,
  METHOD_NOT_FOUND: -32601,
  INVALID_PARAMS: -32602,
  INTERNAL_ERROR: -32603,
  VERSION_MISMATCH: -32000,
  APP_ERROR: -32001,
} as const;

export const Method = {
  HELLO: "hello",
  PING: "ping",
} as const;

export const Notification = {
  LOG: "log",
} as const;

export interface HelloParams {
  protocol_version: number;
  client: string;
}

export interface HelloResult {
  ok: boolean;
  protocol_version: number;
  engine_version: string;
  daemon_version: string;
}

export interface PingParams {
}

export interface PingResult {
  pong: boolean;
}

