// AUTOGENERATED by editor/protocol/codegen.py from schema.json — DO NOT EDIT.
/* eslint-disable */

export const PROTOCOL_VERSION = 5;
export const DAEMON_VERSION = "0.1.0";

// Binary framing: [u32 magic][u32 schema_id][u32 payload_id][payload], little-endian.
export const BINARY_MAGIC = 1179210309; // 0x46495245
export const BINARY_HEADER_SIZE = 12;

export const SchemaId = {
  MESH: 1,
  TEXTURE: 2,
} as const;

export const ErrorCode = {
  PARSE_ERROR: -32700,
  INVALID_REQUEST: -32600,
  METHOD_NOT_FOUND: -32601,
  INVALID_PARAMS: -32602,
  INTERNAL_ERROR: -32603,
  VERSION_MISMATCH: -32000,
  APP_ERROR: -32001,
} as const;

export const Method = {
  HELLO: "hello",
  PING: "ping",
  WORLD_OPEN: "world.open",
  WORLD_SAVE: "world.save",
  CHUNKS_SET_CENTER: "chunks.set_center",
  WORLD_GROUND_LUT: "world.ground_lut",
  SCENE_STATS: "scene.stats",
  TERRAIN_RAYCAST: "terrain.raycast",
  TERRAIN_BRUSH: "terrain.brush",
  EDIT_UNDO: "edit.undo",
  EDIT_REDO: "edit.redo",
  SCENE_TREE: "scene.tree",
  SCENE_CREATE: "scene.create",
  SCENE_RENAME: "scene.rename",
  SCENE_REPARENT: "scene.reparent",
  SCENE_SET_TRANSFORM: "scene.set_transform",
  SCENE_DELETE: "scene.delete",
} as const;

export const Notification = {
  LOG: "log",
  CHUNK_READY: "chunk.ready",
  CHUNK_UNLOAD: "chunk.unload",
  STREAM_DONE: "stream.done",
  EDIT_STATE: "edit.state",
  SCENE_CHANGED: "scene.changed",
} as const;

export interface HelloParams {
  protocol_version: number;
  client: string;
}

export interface HelloResult {
  ok: boolean;
  protocol_version: number;
  engine_version: string;
  daemon_version: string;
}

export interface PingParams {
}

export interface PingResult {
  pong: boolean;
}

export interface WorldOpenParams {
  seed?: number;
  save_path?: string;
}

export interface WorldOpenResult {
  ok: boolean;
  seed: number;
  config: unknown;
  edited_chunks: number;
}

export interface WorldSaveParams {
  path: string;
}

export interface WorldSaveResult {
  ok: boolean;
  path: string;
  edited_chunks: number;
}

export interface ChunksSetCenterParams {
  x: number;
  y: number;
  z: number;
  radius?: number;
  resend?: boolean;
}

export interface ChunksSetCenterResult {
  ok: boolean;
  requested: number;
}

export interface WorldGroundLutParams {
}

export interface WorldGroundLutResult {
  ok: boolean;
  payload_id: number;
  width: number;
  height: number;
  ground_seed: number;
  ground_texels_per_m: number;
}

export interface SceneStatsParams {
}

export interface SceneStatsResult {
  chunks_loaded: number;
  meshed: number;
  vertices: number;
  triangles: number;
}

export interface TerrainRaycastParams {
  ox: number;
  oy: number;
  oz: number;
  dx: number;
  dy: number;
  dz: number;
  max_distance?: number;
}

export interface TerrainRaycastResult {
  hit: unknown;
}

export interface TerrainBrushParams {
  shape: string;
  x: number;
  y: number;
  z: number;
  mode: string;
  material?: number;
  radius?: number;
  hx?: number;
  hy?: number;
  hz?: number;
  height?: number;
}

export interface TerrainBrushResult {
  ok: boolean;
  touched: number;
  can_undo: boolean;
  can_redo: boolean;
}

export interface EditUndoParams {
}

export interface EditUndoResult {
  ok: boolean;
  touched: number;
  label: string;
  can_undo: boolean;
  can_redo: boolean;
}

export interface EditRedoParams {
}

export interface EditRedoResult {
  ok: boolean;
  touched: number;
  label: string;
  can_undo: boolean;
  can_redo: boolean;
}

export interface SceneTreeParams {
}

export interface SceneTreeResult {
  objects: unknown;
}

export interface SceneCreateParams {
  kind: string;
  parent?: number;
  name?: string;
  x?: number;
  y?: number;
  z?: number;
}

export interface SceneCreateResult {
  ok: boolean;
  object: unknown;
}

export interface SceneRenameParams {
  id: number;
  name: string;
}

export interface SceneRenameResult {
  ok: boolean;
  object: unknown;
}

export interface SceneReparentParams {
  id: number;
  parent?: number;
}

export interface SceneReparentResult {
  ok: boolean;
  object: unknown;
}

export interface SceneSetTransformParams {
  id: number;
  px?: number;
  py?: number;
  pz?: number;
  rw?: number;
  rx?: number;
  ry?: number;
  rz?: number;
  sx?: number;
  sy?: number;
  sz?: number;
}

export interface SceneSetTransformResult {
  ok: boolean;
  object: unknown;
}

export interface SceneDeleteParams {
  id: number;
}

export interface SceneDeleteResult {
  ok: boolean;
  removed: unknown;
}

