"""AUTOGENERATED by editor/protocol/codegen.py from schema.json — DO NOT EDIT."""
from __future__ import annotations

from typing import TypedDict

PROTOCOL_VERSION = 1
DAEMON_VERSION = "0.1.0"

# Binary framing: [u32 magic][u32 schema_id][u32 payload_id][payload], little-endian.
BINARY_MAGIC = 1179210309  # 0x46495245
BINARY_HEADER_SIZE = 12

class SchemaId:
    MESH = 1
    TEXTURE = 2

class ErrorCode:
    PARSE_ERROR = -32700
    INVALID_REQUEST = -32600
    METHOD_NOT_FOUND = -32601
    INVALID_PARAMS = -32602
    INTERNAL_ERROR = -32603
    VERSION_MISMATCH = -32000
    APP_ERROR = -32001

class Method:
    HELLO = "hello"
    PING = "ping"

class Notification:
    LOG = "log"

class HelloParams(TypedDict):
    protocol_version: int
    client: str

class HelloResult(TypedDict):
    ok: bool
    protocol_version: int
    engine_version: str
    daemon_version: str

class PingParams(TypedDict):
    pass

class PingResult(TypedDict):
    pong: bool

