"""AUTOGENERATED by editor/protocol/codegen.py from schema.json — DO NOT EDIT."""

from __future__ import annotations

from typing import NotRequired, TypedDict

PROTOCOL_VERSION = 6
DAEMON_VERSION = "0.1.0"

# Binary framing: [u32 magic][u32 schema_id][u32 payload_id][payload], little-endian.
BINARY_MAGIC = 1179210309  # 0x46495245
BINARY_HEADER_SIZE = 12


class SchemaId:
    MESH = 1
    TEXTURE = 2


class ErrorCode:
    PARSE_ERROR = -32700
    INVALID_REQUEST = -32600
    METHOD_NOT_FOUND = -32601
    INVALID_PARAMS = -32602
    INTERNAL_ERROR = -32603
    VERSION_MISMATCH = -32000
    APP_ERROR = -32001


class Method:
    HELLO = "hello"
    PING = "ping"
    WORLD_OPEN = "world.open"
    WORLD_SAVE = "world.save"
    CHUNKS_SET_CENTER = "chunks.set_center"
    WORLD_GROUND_LUT = "world.ground_lut"
    SCENE_STATS = "scene.stats"
    TERRAIN_RAYCAST = "terrain.raycast"
    TERRAIN_BRUSH = "terrain.brush"
    EDIT_UNDO = "edit.undo"
    EDIT_REDO = "edit.redo"
    SCENE_TREE = "scene.tree"
    SCENE_CATALOG = "scene.catalog"
    SCENE_CREATE = "scene.create"
    SCENE_RENAME = "scene.rename"
    SCENE_REPARENT = "scene.reparent"
    SCENE_SET_TRANSFORM = "scene.set_transform"
    SCENE_DELETE = "scene.delete"
    SCENE_ADD_COMPONENT = "scene.add_component"
    SCENE_REMOVE_COMPONENT = "scene.remove_component"
    SCENE_SET_COMPONENT = "scene.set_component"


class Notification:
    LOG = "log"
    CHUNK_READY = "chunk.ready"
    CHUNK_UNLOAD = "chunk.unload"
    STREAM_DONE = "stream.done"
    EDIT_STATE = "edit.state"
    SCENE_CHANGED = "scene.changed"


class HelloParams(TypedDict):
    protocol_version: int
    client: str


class HelloResult(TypedDict):
    ok: bool
    protocol_version: int
    engine_version: str
    daemon_version: str


class PingParams(TypedDict):
    pass


class PingResult(TypedDict):
    pong: bool


class WorldOpenParams(TypedDict):
    seed: NotRequired[int]
    save_path: NotRequired[str]


class WorldOpenResult(TypedDict):
    ok: bool
    seed: int
    config: object
    edited_chunks: int


class WorldSaveParams(TypedDict):
    path: str


class WorldSaveResult(TypedDict):
    ok: bool
    path: str
    edited_chunks: int


class ChunksSetCenterParams(TypedDict):
    x: float
    y: float
    z: float
    radius: NotRequired[int]
    resend: NotRequired[bool]


class ChunksSetCenterResult(TypedDict):
    ok: bool
    requested: int


class WorldGroundLutParams(TypedDict):
    pass


class WorldGroundLutResult(TypedDict):
    ok: bool
    payload_id: int
    width: int
    height: int
    ground_seed: float
    ground_texels_per_m: float


class SceneStatsParams(TypedDict):
    pass


class SceneStatsResult(TypedDict):
    chunks_loaded: int
    meshed: int
    vertices: int
    triangles: int


class TerrainRaycastParams(TypedDict):
    ox: float
    oy: float
    oz: float
    dx: float
    dy: float
    dz: float
    max_distance: NotRequired[float]


class TerrainRaycastResult(TypedDict):
    hit: object


class TerrainBrushParams(TypedDict):
    shape: str
    x: float
    y: float
    z: float
    mode: str
    material: NotRequired[int]
    radius: NotRequired[float]
    hx: NotRequired[float]
    hy: NotRequired[float]
    hz: NotRequired[float]
    height: NotRequired[float]


class TerrainBrushResult(TypedDict):
    ok: bool
    touched: int
    can_undo: bool
    can_redo: bool


class EditUndoParams(TypedDict):
    pass


class EditUndoResult(TypedDict):
    ok: bool
    touched: int
    label: str
    can_undo: bool
    can_redo: bool


class EditRedoParams(TypedDict):
    pass


class EditRedoResult(TypedDict):
    ok: bool
    touched: int
    label: str
    can_undo: bool
    can_redo: bool


class SceneTreeParams(TypedDict):
    pass


class SceneTreeResult(TypedDict):
    objects: object


class SceneCatalogParams(TypedDict):
    pass


class SceneCatalogResult(TypedDict):
    types: object


class SceneCreateParams(TypedDict):
    kind: str
    parent: NotRequired[int]
    name: NotRequired[str]
    x: NotRequired[float]
    y: NotRequired[float]
    z: NotRequired[float]


class SceneCreateResult(TypedDict):
    ok: bool
    object: object


class SceneRenameParams(TypedDict):
    id: int
    name: str


class SceneRenameResult(TypedDict):
    ok: bool
    object: object


class SceneReparentParams(TypedDict):
    id: int
    parent: NotRequired[int]


class SceneReparentResult(TypedDict):
    ok: bool
    object: object


class SceneSetTransformParams(TypedDict):
    id: int
    px: NotRequired[float]
    py: NotRequired[float]
    pz: NotRequired[float]
    rw: NotRequired[float]
    rx: NotRequired[float]
    ry: NotRequired[float]
    rz: NotRequired[float]
    sx: NotRequired[float]
    sy: NotRequired[float]
    sz: NotRequired[float]


class SceneSetTransformResult(TypedDict):
    ok: bool
    object: object


class SceneDeleteParams(TypedDict):
    id: int


class SceneDeleteResult(TypedDict):
    ok: bool
    removed: object


class SceneAddComponentParams(TypedDict):
    id: int
    type: str


class SceneAddComponentResult(TypedDict):
    ok: bool
    object: object


class SceneRemoveComponentParams(TypedDict):
    id: int
    index: int


class SceneRemoveComponentResult(TypedDict):
    ok: bool
    object: object


class SceneSetComponentParams(TypedDict):
    id: int
    index: int
    params: NotRequired[object]
    enabled: NotRequired[bool]


class SceneSetComponentResult(TypedDict):
    ok: bool
    object: object
